# Generated by Django 3.2.12 on 2022-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='email',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
